### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by Cookiemonster75** [toasterofbread/spmp#416]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Click download and nothing happens. When I force stop the app and reopen I get the error. 

### Expected behavior

Should download the song

### Actual behavior

Nothing then error

### Screenshots / recordings

java.lang.RuntimeException: No valid formats returned by getVideoFormats(IeW9F4sGzf0)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt.getSongFormats(Unknown Source:134)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt$getSongFormats$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
	at androidx.concurrent.futures.ToContinuation.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:92)

### Logs

java.lang.RuntimeException: No valid formats returned by getVideoFormats(IeW9F4sGzf0)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt.getSongFormats(Unknown Source:134)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt$getSongFormats$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
	at androidx.concurrent.futures.ToContinuation.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:92)

### SpMp version

0.4.2

### SpMp platform

Android

### OS version

Android 15

### Additional information

None

**Comment by toasterofbread** [comment]
Which commit did you test this with?

**Comment by Cookiemonster75** [comment]
This is the very latest build.

**Comment by Cookiemonster75** [comment]
This is the notification which keeps popping up -

java.lang.RuntimeException: No valid formats returned by getVideoFormats(IeW9F4sGzf0)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt.getSongFormats(Unknown Source:134)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt$getSongFormats$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:106)
	at androidx.concurrent.futures.ToContinuation.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:92)

**Comment by toasterofbread** [comment]
Please confirm which commit you've tested. There have been a lot of changes recently around stream fetching (due to YouTube's changes) so I just want to be sure.

**Comment by Cookiemonster75** [comment]
I am on commit 415.

**Comment by toasterofbread** [comment]
What do you mean by 415? Could you provide a commit hash or link?

**Comment by Cookiemonster75** [comment]
I thought it was maybe my storage access but I cleared app data and reinstalled.

**Comment by Cookiemonster75** [comment]
Sorry if I sound a bit silly. https://github.com/toasterofbread/spmp/actions/runs/12333875235

**Comment by toasterofbread** [comment]
This is an ongoing issue caused by YouTube constantly changing their API and making it harder for third-party clients to stream audio. There's currently no solution I know of, and even if I did it probably wouldn't work in a few weeks.

Potential workaround:
1. Make sure you're using the latest nightly build on the main branch
2. If that doesn't work out of the box, switch the song stream method to NewPipe and/or enable stream method fallbacks
3. If that doesn't work and you're signed in to YTM, try signing out and restarting the app, and use the Youtubei stream method

Will keep this issue open.

**Comment by toasterofbread** [comment]
See also: https://github.com/TeamNewPipe/NewPipe/issues/11139

**Comment by ZZMM1409** [comment]
M

**Comment by Samad-31** [comment]
![Screenshot_2025-01-06-23-05-26-314_com toasterofbread spmp](https://github.com/user-attachments/assets/70cd1671-be3a-4647-9a8a-eb31039b3409)

Use Newpipe as play/download

**Comment by MD77MD** [comment]
here is a summery of what's going on:

1. if you chose to download to spmp library , it will download in mp4 format. (only one song per app lunch )

2. but if you chose to download to a custom location , it will download into m4p format but woth (0) Byte.


3. if you want to download multiple songs, you must force close and relunch the app before every song download ... does the Continuous permanently looping download notification have to do anything with this?

4. Download only works with youtubei and newpipe, does not work with piped Api... streaming works with all.

5. when downloading a song, spmp loss its link with previous song. so it shows the correct thumbnail of the last song in Library download songs section. (almost like it writes over the previous song) 

using Nightly 2025-01-08 15:45:19

**Comment by coder-eb** [comment]
> <img src="https://github.com/user-attachments/assets/70cd1671-be3a-4647-9a8a-eb31039b3409" height=600px>
> 
> Use Newpipe as play/download 

Which version are you using?

**Comment by Samad-31** [comment]
> > <img alt="" height="600px" src="https://private-user-images.githubusercontent.com/174238282/400503478-70cd1671-be3a-4647-9a8a-eb31039b3409.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3MjgyOTUsIm5iZiI6MTczODcyNzk5NSwicGF0aCI6Ii8xNzQyMzgyODIvNDAwNTAzNDc4LTcwY2QxNjcxLWJlM2EtNDY0Ny05YThhLWViMzEwMzliMzQwOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwNVQwMzU5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2YwOThlYzM2MmM1ZTIzMTYzZTAwZDEzNmFmZDY4NDYyMGNhZmQ2NzU0NDgzZjhiNDc3NmYyNGZhMjEzMjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DVu6HwHSLe0qpxfMv0VLysjhi7ijG9D532TSC3rLkfA">
> > Use Newpipe as play/download
> 
> Which version are you using?

Latest available on GitHub

**Comment by kairusds** [comment]
What about a client switcher like the one from Musify?

**Comment by coder-eb** [comment]
> > > <img alt="" height="600px" src="https://private-user-images.githubusercontent.com/174238282/400503478-70cd1671-be3a-4647-9a8a-eb31039b3409.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3MjgyOTUsIm5iZiI6MTczODcyNzk5NSwicGF0aCI6Ii8xNzQyMzgyODIvNDAwNTAzNDc4LTcwY2QxNjcxLWJlM2EtNDY0Ny05YThhLWViMzEwMzliMzQwOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwNVQwMzU5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2YwOThlYzM2MmM1ZTIzMTYzZTAwZDEzNmFmZDY4NDYyMGNhZmQ2NzU0NDgzZjhiNDc3NmYyNGZhMjEzMjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DVu6HwHSLe0qpxfMv0VLysjhi7ijG9D532TSC3rLkfA">
> > > Use Newpipe as play/download
> > 
> > 
> > Which version are you using?
> 
> Latest available on f droid


Is it working for you? I'm using the same version but it does not load.

**Comment by toasterofbread** [comment]
The latest release (on all platforms) is practically ancient, I'd recommend using a nightly build.

**Comment by coder-eb** [comment]
> The latest release (on all platforms) is practically ancient, I'd recommend using a nightly build.

It's working in the nightly build. Awesome!

**Comment by kairusds** [comment]
> > The latest release (on all platforms) is practically ancient, I'd recommend using a nightly build.
> 
> It's working in the nightly build. Awesome!

Can confirm it's also working, though I had to relogin with YT Music and wait for a few seconds for songs to load.

**Comment by Newbytee** [comment]
> The latest release (on all platforms) is practically ancient, I'd recommend using a nightly build.

Are there any plans to make a new release soon then? I don't see any way of installing nightly as a Flatpak short of building it myself.

**Comment by wait-what** [comment]
In my case, it takes 10 minutes or so for the first song to play, then it works properly for a while.

**Comment by MD77MD** [comment]
is this app dead or what? other streaming apps are already fixed and updated ... i prefer this app but what's the point if its not working

**Comment by R-N** [comment]
Have you tried nightly build?

Can you provide example of the other apps that got it fixed? It might help as reference

**Comment by toasterofbread** [comment]
> Can you provide example of the other apps that got it fixed? It might help
as reference

This would be appreciated. I'm not actively maintaining SpMp at the moment, but if an actual fix is discovered I'll probably implement it.

The main branch should be working with NewPipeExtractor at the moment, as that was updated recently.

**Comment by R-N** [comment]
> The main branch should be working with NewPipeExtractor at the moment, as that was updated recently.

Newpipe playback on latest nightly (from few minutes ago, 5a76563) still broken for me

**Comment by MD77MD** [comment]
@toasterofbread from my testing harmony music from F-droid is working

**Comment by Tyriqscott** [comment]
When you get a new version of spmp?

**Comment by MD77MD** [comment]
are there any.plans to fix this soon.... please let us know weather to keep the app or not

**Comment by sayaka-sh** [comment]
@MD77MD I'd like to revisit spmp once my current project wraps up, but no concrete plans at the moment.
