### ISSUE TITLE
Clicking "Artist Info(?)" Shows RuntimeException Error

### ISSUE THREAD

**Issue by farsdewibs0n** [toasterofbread/spmp#439]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

While a song is playing, show click the "Artist Info (I don't know what button is this exactly, since so far I only see error when I clicked it)" button (left of "All" button).

### Expected behavior

Information related to the icon should appear.

### Actual behavior

Shows RuntimeException error.

### Screenshots / recordings

![image](https://github.com/user-attachments/assets/341073ea-9191-4eef-885c-1a2325477996)

### Logs

http://paste.ee/0Ccw9

### SpMp version

0.4.2

### SpMp platform

Windows

### OS version

Windows 10

### Additional information

Clicking copy doesn't work, had to type the log URL manually.

**Comment by toasterofbread** [comment]
This should have been fixed recently, could you confirm the latest build/commit you tested this with please?

**Comment by farsdewibs0n** [comment]
Still broken:
![image](https://github.com/user-attachments/assets/a9132ce9-6947-4543-a6f0-7192003a1930)


Just making sure, I grabbed it from https://nightly.link/toasterofbread/spmp/workflows/build-windows/main.

**Comment by farsdewibs0n** [comment]
An extra (idk if I should add a new issue since it's related to this issue). Copying the RuntimeException error via right-clicking doesn't work.
![image](https://github.com/user-attachments/assets/6372a2a5-7635-4383-99a1-5b9eda800d37)
